version: '2.0'
services:
  app:
    build: .
    networks:
      - default
    restart: always
    ports:
      - "80:80"
    labels:
      - "traefik.docker.network=web"
      - "traefik.basic.frontend.rule=Host:cov19uk.info,www.cov19uk.info"
      - "traefik.port=80"